# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-23 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('state', models.IntegerField(choices=[(0, '\u6709\u6548'), (1, '\u4e34\u65f6\u8bb0\u5f55'), (9, '\u5220\u9664')], default=0)),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('alias_name', models.CharField(default='', max_length=32, verbose_name='\u7c7b\u76ee\u522b\u540d')),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='\u6df1\u5ea6')),
                ('order_id', models.PositiveIntegerField(default=0, verbose_name='\u987a\u5e8fid')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_key', to='myfarm.Category', verbose_name='\u7236\u7ea7\u7c7b\u76ee,\u8be5\u5b57\u6bb5\u4e3a\u7a7a\u65f6\u8868\u793a\u6839\u7c7b\u76ee')),
            ],
            options={
                'verbose_name': '\u7c7b\u76ee',
                'verbose_name_plural': '\u7c7b\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('state', models.IntegerField(choices=[(0, '\u6709\u6548'), (1, '\u4e34\u65f6\u8bb0\u5f55'), (9, '\u5220\u9664')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (10, '\u5f85\u5ba1\u6838'), (20, '\u7ba1\u7406\u5458\u5ba1\u6838\u4e2d'), (30, '\u7ba1\u7406\u5458\u5ba1\u6838\u672a\u901a\u8fc7'), (40, '\u7ba1\u7406\u5458\u5ba1\u6838\u901a\u8fc7'), (50, '\u5df2\u5165\u5e93')], db_index=True, default=0, verbose_name='\u6a21\u578b\u72b6\u6001')),
                ('render_state', models.IntegerField(choices=[(0, '\u672a\u6e32\u67d3'), (1, '\u6392\u961f\u4e2d(\u5df2\u53d1\u5f80\u6e32\u67d3\u519c\u573a)'), (2, '\u6e32\u67d3\u4e2d'), (3, '\u6e32\u67d3\u5b8c\u6210'), (4, '\u6e32\u67d3\u5931\u8d25')], default=0, verbose_name='\u6e32\u67d3\u72b6\u6001')),
                ('photo_degree', models.SmallIntegerField(choices=[(0, '\u65e0'), (45, '45\u5ea6\u4e00\u5f20'), (1, '1\u5ea6\u4e00\u5f20')], default=0, verbose_name='\u6a21\u578b\u73af\u7ed5\u7167\u7247\u6e32\u67d3\u7684\u89d2\u5ea6\u95f4\u9694\uff0c\u6bcf\u969445\u5ea6,\u6bcf\u96941\u5ea6\uff0c0\u4e3a\u9ed8\u8ba4')),
                ('inner_type', models.PositiveIntegerField(choices=[(1, '\u5bb6\u5177'), (2, '\u95e8'), (3, '\u7a97'), (4, '\u6750\u8d28'), (5, '\u7ebf\u6761'), (6, '\u6846\u67b6')], default=1, verbose_name='\u5185\u90e8\u5206\u7c7b')),
                ('sub_type', models.PositiveIntegerField(choices=[(101, 'DEFAULT\u6a21\u578b'), (102, 'TOP\u6a21\u578b'), (103, 'BOTTOM\u6a21\u578b'), (104, 'BACKEND\u6a21\u578b'), (105, 'FLOOR\u6a21\u578b'), (106, 'ROOF_DEFAULT\u6a21\u578b'), (107, 'ROOF_BOTTOM\u6a21\u578b'), (108, 'ROOF_TOP\u6a21\u578b'), (109, 'ROOF_TOP_PLUS\u6a21\u578b'), (110, '\u9ed8\u8ba4\u9876\u90e8\u6a21\u578b'), (111, '\u540a\u9876'), (201, '\u5355\u5f00\u95e8'), (202, '\u53cc\u5f00\u95e8'), (203, '\u63a8\u62c9\u95e8'), (204, '\u95e8\u5957'), (301, '\u666e\u901a\u7a97'), (302, '\u98d8\u7a97'), (303, '\u843d\u5730\u7a97'), (401, '\u5730\u9762\u6750\u8d28'), (402, '\u5899\u9762\u6750\u8d28'), (403, '\u8e22\u811a\u7ebf\u6750\u8d28'), (404, '\u9876\u9762\u6750\u8d28'), (501, '\u6a71\u67dc\u811a\u7ebf'), (502, '\u6a71\u67dc\u53f0\u9762\u524d\u6321\u6c34\u7ebf'), (503, '\u6a71\u67dc\u53f0\u9762\u540e\u6321\u6c34\u7ebf'), (504, '\u6a71\u67dc\u540a\u67dc\u9876\u7ebf'), (600, '\u6a71\u67dc\u9ed8\u8ba4\u6846\u67b6'), (601, '\u6a71\u67dc\u5730\u67dc\u6846\u67b6'), (602, '\u6a71\u67dc\u4e2d\u67dc\u6846\u67b6'), (603, '\u6a71\u67dc\u9ad8\u67dc\u6846\u67b6'), (604, '\u6a71\u67dc\u9876\u67dc\u6846\u67b6'), (700, '\u8863\u67dc\u5355\u5143\u67dc\u6846\u67b6')], default=101, verbose_name='\u5b50\u5206\u7c7b')),
                ('system_type', models.SmallIntegerField(choices=[(0, '\u9ed8\u8ba4'), (101, '\u67dc\u67b6\u5b9a\u5236-\u67dc\u95e8'), (102, '\u67dc\u67b6\u5b9a\u5236-\u62bd\u5c49'), (103, '\u67dc\u67b6\u5b9a\u5236-\u6302\u6746'), (200, '\u540a\u9876\u5b9a\u5236-\u9ed8\u8ba4'), (201, '\u540a\u9876\u5b9a\u5236-\u89d2\u7ebf'), (400, '\u6a71\u67dc\u5b9a\u5236'), (401, '\u6a71\u67dc\u5b9a\u5236-\u5355\u5143\u67dc'), (402, '\u6a71\u67dc\u5b9a\u5236-\u677f\u4ef6'), (403, '\u6a71\u67dc\u5b9a\u5236-\u811a\u7ebf'), (404, '\u6a71\u67dc\u5b9a\u5236-\u95e8\u677f'), (405, '\u6a71\u67dc\u5b9a\u5236-\u628a\u624b'), (500, '\u533a\u57df\u94fa\u8d34'), (501, '\u533a\u57df\u94fa\u8d34-\u74f7\u7816'), (502, '\u533a\u57df\u94fa\u8d34-\u5730\u677f'), (505, '\u533a\u57df\u94fa\u8d34-\u6ce2\u6253\u7ebf'), (510, '\u533a\u57df\u94fa\u8d34-\u6837\u5f0f'), (600, '\u8863\u67dc\u5b9a\u5236'), (700, '\u62a4\u5899\u677f\u5b9a\u5236'), (701, '\u9f99\u9aa8'), (702, '\u5899\u677f'), (703, '\u7ebf\u6761')], default=0, verbose_name='\u5b50\u7cfb\u7edf\u5206\u7c7b')),
                ('is_public', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('lightable', models.SmallIntegerField(choices=[(0, '\u65e0\u706f\u5149'), (1, '\u9ed8\u8ba4\u5149'), (2, '\u9762\u706f\u5149'), (3, '\u7403\u706f\u5149'), (4, 'IES\u5149')], default=0, verbose_name='\u643a\u5e26\u5149\u6e90\u7c7b\u578b')),
                ('scalable', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, verbose_name='\u662f\u5426\u53ef\u7f29\u653e')),
                ('direct_scalable', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='\u662f\u5426\u53ef\u4ee5\u5355\u5411\u7f29\u653e')),
                ('salable', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='\u662f\u5426\u9500\u552e')),
                ('product_width', models.FloatField(default=0, verbose_name='\u7269\u54c1\u6a21\u578b\u5bbd\u5ea6\uff0c\u5355\u4f4dcm')),
                ('product_length', models.FloatField(default=0, verbose_name='\u7269\u54c1\u6a21\u578b\u957f\u5ea6\uff0c\u5355\u4f4dcm')),
                ('product_height', models.FloatField(default=0, verbose_name='\u7269\u54c1\u6a21\u578b\u9ad8\u5ea6\uff0c\u5355\u4f4dcm')),
                ('flat_height', models.FloatField(default=0, verbose_name='\u7269\u54c1\u6a21\u578b\u5e73\u53f0\u9ad8\u5ea6\uff0c\u5355\u4f4dcm')),
                ('product_name', models.CharField(max_length=64, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('product_id', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='\u5546\u54c1id')),
                ('sku_id', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='skuid')),
                ('product_link', models.CharField(blank=True, default='', max_length=512, verbose_name='\u4ea7\u54c1\u94fe\u63a5')),
                ('product_brand', models.CharField(blank=True, default='', max_length=64, verbose_name='\u4ea7\u54c1\u54c1\u724c')),
                ('product_price', models.FloatField(default=0, verbose_name='\u4ea7\u54c1\u4ef7\u683c')),
                ('width', models.FloatField(default=0, verbose_name='\u4ea7\u54c1\u771f\u5b9e\u5bbd\u5ea6\uff0c\u5355\u4f4dcm')),
                ('length', models.FloatField(default=0, verbose_name='\u4ea7\u54c1\u771f\u5b9e\u957f\u5ea6\uff0c\u5355\u4f4dcm')),
                ('height', models.FloatField(default=0, verbose_name='\u4ea7\u54c1\u771f\u5b9e\u9ad8\u5ea6\uff0c\u5355\u4f4dcm')),
                ('sale_count', models.IntegerField(default=0, verbose_name='\u9500\u91cf')),
                ('group_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='\u6240\u5c5e\u5546\u5bb6')),
                ('material', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u6750\u8d28')),
                ('describe', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='\u63cf\u8ff0')),
                ('cargo_no', models.CharField(blank=True, default='', max_length=64, verbose_name='\u4ea7\u54c1\u8d27\u53f7')),
                ('unit', models.PositiveIntegerField(choices=[(1, '\u4ef6'), (2, '\u5957'), (3, '\u5757'), (4, '\u76cf'), (5, '\u5f20'), (6, '\u4e2a'), (7, 'm'), (8, '\u33a1'), (9, '\u76c6'), (10, '\u6a18'), (11, '\u7247'), (12, '\u7ec4'), (13, '\u6761'), (14, '\u9879'), (15, '\u5377'), (16, '\u6876'), (17, '\u5ea7'), (18, '\u6b65')], default=1, verbose_name='\u4ea7\u54c1\u5355\u4f4d')),
                ('discount_price', models.IntegerField(default=0, verbose_name='\u6298\u6263\u4ef7\u683c(\u5355\u4f4d-\u5206)')),
                ('photo_scale', models.FloatField(default=1.4, verbose_name='\u6a21\u578b\u6e32\u67d3\u7f29\u653e\u6bd4\u4f8b')),
                ('preview_fpath', models.CharField(blank=True, default='', max_length=128, verbose_name='\u9884\u89c8\u56fe\u8def\u5f84')),
                ('merchant', models.CharField(blank=True, default='', max_length=128, verbose_name='\u6240\u5c5e\u5546\u5bb6id')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='\u6a21\u578b\u7ba1\u7406\u5458')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u6709\u8005')),
            ],
            options={
                'verbose_name': '\u7269\u54c1',
                'verbose_name_plural': '\u7269\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(db_index=True, max_length=64, verbose_name='\u7269\u54c1\u7f16\u53f7')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfarm.Category', verbose_name='\u7c7b\u76ee')),
            ],
            options={
                'verbose_name': '\u7269\u54c1\u7c7b\u76ee\u5173\u8054',
                'verbose_name_plural': '\u7269\u54c1\u7c7b\u76ee\u5173\u8054',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('app_no', models.IntegerField(default=0)),
                ('domain', models.CharField(max_length=128)),
                ('farm_domain', models.CharField(max_length=128)),
                ('spec', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Unreal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'not convert'), (10, 'converting'), (20, 'convert failed'), (30, 'converted')], default=0)),
                ('real_type', models.IntegerField(choices=[(100, 'uncooked'), (200, 'cooked'), (300, 'ios'), (400, 'android')])),
                ('filename', models.CharField(max_length=128)),
                ('is_exist', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together=set([('item_no', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('parent', 'name')]),
        ),
    ]
